algorithm: tsp

# --- data ---
num_samples:
  train: 10000
  val: 320
  test: 320

problem_size:
  train: 10
  val: 10
  test: 10

edge_weights: true

# --- model ---
num_node_states: 2
num_edge_states: 2
